//
//  LoginRouter.swift
//  VIPLogin
//
//  Created by Leandro Ramos on 10/29/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToRegister(segue: UIStoryboardSegue?)
    func simpleRouterToRegister()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToRegister(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! RegisterViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToRegister(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "RegisterViewController") as! RegisterViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToRegister(source: dataStore!, destination: &destinationDS)
            navigateToRegister(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    func simpleRouterToRegister() {
        viewController?.performSegue(withIdentifier: Constants.Indentifiers.loginSegue, sender: viewController)
    }

    func navigateToRegister(source: LoginViewController, destination: RegisterViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToRegister(source: LoginDataStore, destination: inout RegisterDataStore) {
        destination.userData = source.userData
    }
}
