//
//  LoginPresenter.swift
//  VIPLogin
//
//  Created by Leandro Ramos on 10/29/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentLogin(response: LoginModel.Fetch.Response)
    func presentLoginError(error: String)
    func showMainPageAfterLogin()
}

class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
        
    func presentLogin(response: LoginModel.Fetch.Response) {
        let viewModel = LoginModel.Fetch.ViewModel(token: response.user?.token ?? "",
                                                   name: response.user?.name ?? "",
                                                   email: response.user?.email ?? "",
                                                   password: response.user?.password ?? "",
                                                   statusCode: response.user?.statusCode ?? 0)
        viewController?.getData(viewModel: viewModel)
    }
    
    func presentLoginError(error: String) {
        viewController?.displayErrorAlert(error: error)
    }
    
    func showMainPageAfterLogin() {
        viewController?.transitionToMain()
    }


}
