//
//  MainPageInteractor.swift
//  VIPLogin
//
//  Created by Leandro Ramos on 11/1/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPageBusinessLogic
{
  func doSomething(request: MainPage.Something.Request)
}

protocol MainPageDataStore
{
  //var name: String { get set }
}

class MainPageInteractor: MainPageBusinessLogic, MainPageDataStore
{
  var presenter: MainPagePresentationLogic?
  var worker: MainPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MainPage.Something.Request)
  {
    worker = MainPageWorker()
    worker?.doSomeWork()
    
    let response = MainPage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
